name: heroku
version: '6.13.1'
summary: Heroku CLI
description: Heroku CLI
grade: stable
confinement: classic

apps:
    heroku:
        command: bin/node $SNAP/lib/node_modules/heroku-cli/bin/run.js

parts:
  heroku:
    source: .
    plugin: nodejs
    node-engine: 8.2.1
    # In Node 8 local projects get symlinked instead of copied. This results in
    # a dangling symlink back to the build directory in snapcraft. So until
    # http://pad.lv/1702661 is fixed, copy heroku-cli in place.
    install: |
        heroku_cli=$SNAPCRAFT_PART_INSTALL/lib/node_modules/heroku-cli
        rm $heroku_cli
        cp -r . $heroku_cli/
